version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop-management-system
    ports:
      - "3000:80"
    environment:
      - NODE_ENV=production