name: Deploy to Server

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to server
      env:
        PRIVATE_KEY: ${{ secrets.SERVER_SSH_PRIVATE_KEY }}
        HOST: ${{ secrets.SERVER_HOST }}
        USER: ${{ secrets.SERVER_USER }}
        PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
        FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
        FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
        FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
        FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}
      run: |
        echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
        ssh -o StrictHostKeyChecking=no -i private_key ${USER}@${HOST} '
          sudo chmod 666 /run/docker.sock
          cd ${PROJECT_PATH} &&
          git pull origin main &&
          /snap/bin/docker build \
            --build-arg VITE_FIREBASE_API_KEY='"'"'${FIREBASE_API_KEY}'"'"' \
            --build-arg VITE_FIREBASE_AUTH_DOMAIN='"'"'${FIREBASE_AUTH_DOMAIN}'"'"' \
            --build-arg VITE_FIREBASE_PROJECT_ID='"'"'${FIREBASE_PROJECT_ID}'"'"' \
            --build-arg VITE_FIREBASE_STORAGE_BUCKET='"'"'${FIREBASE_STORAGE_BUCKET}'"'"' \
            --build-arg VITE_FIREBASE_MESSAGING_SENDER_ID='"'"'${FIREBASE_MESSAGING_SENDER_ID}'"'"' \
            --build-arg VITE_FIREBASE_APP_ID='"'"'${FIREBASE_APP_ID}'"'"' \
            --build-arg VITE_FIREBASE_MEASUREMENT_ID='"'"'${FIREBASE_MEASUREMENT_ID}'"'"' \
            -t workshop-managementwo . &&
          /snap/bin/docker stop workshop-container || true &&
          /snap/bin/docker rm workshop-container || true &&
          /snap/bin/docker run -d --name workshop-container -p 3000:80 workshop-managementwo
        '
